name: honeybee
description: A social media dating app project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  awesome_notifications: ^0.9.1
  build_runner: ^2.4.6
  cached_network_image: ^3.3.1
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  dartz: ^0.10.1
  dio: ^5.4.1
  emoji_picker_flutter: ^1.6.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_pin_code_fields: ^2.2.0
  font_awesome_flutter: ^10.5.0
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  http: ^1.1.0
  http_parser: ^4.0.2
  image_picker: ^1.0.4
  intl: ^0.19.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  loading_animation_widget: ^1.2.1
  lottie: ^2.7.0
  permission_handler: ^10.4.5
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.0-beta.4-nullsafety.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/
  fonts:
    - family: Montez-Regular
      fonts:
        - asset: assets/fonts/Montez-Regular.ttf
    - family: MetroNovaPro-Regular
      fonts:
        - asset: assets/fonts/MetroNovaPro-Regular.otf
    - family: Sk-Modernist-Regular
      fonts:
        # - asset: assets/fonts/Sk-Modernist-Bold.ttf
        # - asset: assets/fonts/Sk-Modernist-Mono.ttf
        - asset: assets/fonts/Sk-Modernist-Regular.ttf
